services:
  birthday-bot:
    container_name: birthday_bot
    image: ghcr.io/bogdan2913/birthday-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./images:/app/images
    environment:
      TOKEN: "${TOKEN}"



