version: '3.8'
services:
  birthday-bot:
    image: python:3.11-slim   # <-- вместо build
    container_name: birthday_bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./images:/app/images
    environment:
      TOKEN: "${TOKEN}"




